// <auto-generated />
using GradeManagement.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GradeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204094510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GradeManagement.Entity.Course", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("GradeManagement.Entity.Result", b =>
                {
                    b.Property<string>("sid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cid")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("grade")
                        .HasColumnType("float");

                    b.HasKey("sid", "cid");

                    b.ToTable("result", (string)null);
                });

            modelBuilder.Entity("GradeManagement.Entity.User", b =>
                {
                    b.Property<string>("id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("user", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GradeManagement.Entity.Admin", b =>
                {
                    b.HasBaseType("GradeManagement.Entity.User");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("GradeManagement.Entity.FManager", b =>
                {
                    b.HasBaseType("GradeManagement.Entity.User");

                    b.Property<string>("fid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("fManager", (string)null);
                });

            modelBuilder.Entity("GradeManagement.Entity.Student", b =>
                {
                    b.HasBaseType("GradeManagement.Entity.User");

                    b.Property<string>("fid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("GradeManagement.Entity.Admin", b =>
                {
                    b.HasOne("GradeManagement.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("GradeManagement.Entity.Admin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeManagement.Entity.FManager", b =>
                {
                    b.HasOne("GradeManagement.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("GradeManagement.Entity.FManager", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GradeManagement.Entity.Student", b =>
                {
                    b.HasOne("GradeManagement.Entity.User", null)
                        .WithOne()
                        .HasForeignKey("GradeManagement.Entity.Student", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
